version: '3.8'

services:

  # ===== DVWA - Ứng dụng web mục tiêu (nạn nhân) =====
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    restart: unless-stopped
    networks:
      - webids-net

  # ===== ModSecurity + Nginx - Lá chắn WAF =====
  modsecurity:
    image: owasp/modsecurity-crs:nginx
    container_name: modsecurity
    restart: unless-stopped
    environment:
      - BACKEND=http://dvwa:80
      - PARANOIA=1
      - ANOMALY_INBOUND=5
      - ANOMALY_OUTBOUND=4
      - MODSEC_AUDIT_LOG_FORMAT=JSON
      - MODSEC_AUDIT_LOG=/var/log/custom_audit.log
      - MODSEC_RULE_ENGINE=On
    volumes:
      - ./logs/modsec_audit.log:/var/log/custom_audit.log:rw
      - ./modsecurity/ratelimit.conf:/etc/modsecurity.d/owasp-crs/rules/zz-ratelimit.conf:ro
    ports:
      - "80:8080"
    depends_on:
      - dvwa
    networks:
      - webids-net
  # ===== Elasticsearch - Lưu trữ log =====
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - webids-net

  # ===== Kibana - Dashboard hiển thị =====
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - webids-net

# ===== Filebeat - Đẩy log =====
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.0
    container_name: filebeat
    user: root
    # Cập nhật: Thêm lệnh này để ép Filebeat bỏ qua kiểm tra phân quyền
    command: ["--strict.perms=false"]
    restart: unless-stopped
    depends_on:
      - elasticsearch
    networks:
      - webids-net
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs/modsec_audit.log:/var/log/modsec_audit.log:ro
networks:
  webids-net:
    driver: bridge
